chatbox/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.conf.urls import url

from . import views

app_name = 'chatbox'

urlpatterns = [
    path('', TemplateView.as_view(template_name='chatbox/login.html'), name='login'),
    path('conversations', views.new_user, name='loggedin'),
    #path('newconvo', views.new_convo, name='new_convo'),
    #path('message', views.new_message, name='messages'),
    url(r'^(?P<room_name>[^/]+)/$', views.room, name='room')
]

minor_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chatbox/', include('chatbox.urls')),
]

chatbox/models.py
from django.db import models
import uuid
from django.core.validators import MinLengthValidator

# Create your models here.

class User(models.Model):
    user_name = models.CharField(max_length=50)
    roll_no = models.CharField(primary_key=True, default=uuid.uuid4, editable=False, max_length=12, validators=[MinLengthValidator(12)])

    def __str__ (self):
        return self.user_name

#class Conversation(models.Model):
#    conversation_id = models.CharField(primary_key=True, default=uuid.uuid4, editable=False, max_length=24, validators=[MinLengthValidator(24)])
#    first_member = models.ForeignKey(User, on_delete=models.CASCADE, related_name='first_member')
#    second_member = models.ForeignKey(User, on_delete=models.CASCADE, related_name='second_member')
#
#    def __str__(self):
#        return str(self.first_member + '-' + self.second_member)

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    message = models.TextField()
#    conversation = models.ForeignKey(Conversation, on_delete=models.CASCADE)

    def __str__ (self):
        return self.message

chatbox/views.py
from django.shortcuts import render
from .models import User, Message
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.utils.safestring import mark_safe
import json
# Create your views here.

user_list = []

def new_user(request):
    try:
        current_user = User.objects.get(roll_no=request.POST['roll_no'])
    except User.DoesNotExist:
        current_user = None
    #message_list = Message.objects.all()
    if current_user:
        request.session['user'] = current_user.roll_no
        return render(request, 'chatbox/newconvo.html', {'user':current_user})
    #    return render(request, 'chatbox/chatspace.html', {'user':current_user, 'messages':message_list})
    #    return render(request, 'chatbox/conversations.html', {'user':current_user, 'conversations':conversations, 'ids':ids})
    else:   
        newuser = User.objects.create(user_name=request.POST['username'], roll_no=request.POST['roll_no'])
        request.session['user'] = newuser.roll_no
        conversations = None
        return render(request, 'chatbox/newconvo.html', {'user':newuser})
    #    return render(request, 'chatbox/chatspace.html', {'user':newuser, 'messages':message_list}, )
    #    return render(request, 'chatbox/conversations.html', {'user':newuser, 'conversations':conversations})

#def new_message(request):
#    if request.POST['message_box']:
#        newmessage = Message.objects.create(user=get_object_or_404(User, pk=request.session.get('user')), message=request.POST['message_box'])
#        request.session['user'] = newmessage.user.roll_no
#    message_list = Message.objects.all()
#    request.session.objects.all().reload()
#    return render(request, 'chatbox/chatspace.html', {'user':newmessage.user, 'messages':message_list,})

def new_convo(request):
    current_user = get_object_or_404(User, pk=request.session.get('user')).user_name
    return render(request, 'chatbox/newconvo.html', {'user': current_user})

def room(request, room_name):
    current_user = get_object_or_404(User, pk=request.session.get('user'))
    #convo_name = str(room_name)
    #second_member = convo_name - current_user.roll_no
    #if Conversation.objects.get(pk=room_name):
    #    current_convo = Conversation.objects.get(pk=room_name)
    #else:
    #    Conversation.objects.create(conversation_id=room_name, first_member=current_user, second_member=User.objects.get(roll_no=second_member))
    return render(request, 'chatbox/room.html', {'room_name_json':mark_safe(json.dumps(room_name)), 'user_ob':mark_safe(json.dumps(current_user.user_name)), 'user':current_user, 'user_list':user_list})

chatbox/templates/chatbox/chatspace.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <title>Chatbox</title>
    </head>
    <body>
        <p>
            Welcome {{ user.user_name }}.<br>
        </p>
        {% if messages %}
            {% for message in messages %}
                {% if message.user.roll_no == user.roll_no %}
                    <textarea id="chat-log" cols="100" rows="20" readonly="readonly"></textarea><br/>
                    <span style='color:red; text-align:right'> {{ message.message }} </br></span>
                {% else %}
                    <span style='color:blue; text-align:left'> {{ message.message }} <br></span>
                {% endif %}
            {% endfor %}
        {% else %}
            <p></p>
        {% endif %}
        <form action="{% url 'chatbox:messages' %}" method="post">
            {% csrf_token %}
            <input type="text" name="message_box" id="message" placeholder="type your message here" value=null>
            <input type="submit" value="Send" id="sendmsg">
        </form>
    </body>
</html>

chatbox/templates/chatbox/conversations.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Conversations</title>
</head>
<body>
    <h1>Welcome {{ user.user_name }}</h1>
    {% if conversations and ids %}
    <ul>
        {% for (conversation, convo_id) in zip(conversations, ids) %}
            <li onclick = goto(this); id= {{ convo_id }}>{{ conversation }}</li>
        {% endfor %}
    </ul>
    {% else %}
        No Conversations Found. <a href="{% url 'chatbox:new_convo' %}" id="new_convo">Start a new one.</a> <br>
    {% endif %}
</body>
<script>
    var goto = function (convo) {
        var roomName = convo.id;
        window.location.pathname = '/chatbox/' + roomName + '/';
    };
</script>
</html>

chatbox/templates/chatbox/login.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <title>Chatbox</title>
    </head>

    <body>
        <form action="{% url 'chatbox:loggedin' %}" method="post">
            {% csrf_token %}
            <input type="text" name="roll_no" id="roll_no" placeholder="Roll No."><br>
            <input type="text" name="username" id="user_name" placeholder="User Name"><br>
            <input type="password" name="password" id="user_password" placeholder="Password"><br>
            <input type="submit" value="Enter" id="login">
        </form>
    </body>

    <script>
        document.body.onload = function (e) {
            console.log("hey.........");
        };
            /*document.querySelector('#user_password').onblur = function() {
                var original = document.queryselector('#user_password').value;
            };*/

           /* document.querySelector('#login').onclick = function (e) {
                documen
            };*/
            /*document.querySelector('#roll_no').onkeyup = function(e){
                if (e.keyCode === 13) {
                    e.keycode = 8;
                    document.querySelector('#user_name').focus();
                }
            };
            document.querySelector('#user_name').onkeyup = function(e) {
                if (e.keyCode === 13) {  // enter, return
                    e.keycode = 8;
                    document.querySelector('#login').click();
                }
            };*/
    </script>
</html>

chatbox/templates/chatbox/newconvo.html
<!-- chat/templates/chat/index.html -->
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Rooms</title>
</head>
<body>
    <h1>Welcome {{ user }}.</h1><br>
    With whom would you like to talk??<br/>
    <input id="room-name-input" type="text" size="100" placeholder="Roll No./ ID"/><br/>
    <input id="room-name-submit" type="button" value="Enter"/>
</body>
<script>
    /*var user = {{ user }};*/

    document.body.onload = function(e) {
        console.log("Hello.....");
    };

    document.querySelector('#room-name-input').focus();
    /*document.querySelector('#room-name-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#room-name-submit').click();
        }
    };*/

    document.querySelector('#room-name-submit').onclick = function(e) {
        var roomName = document.querySelector('#room-name-input').value;
        console.log("ready...");
        window.location.pathname = '/chatbox/' + roomName + '/';
    };
</script>
</html>

chatbox/templates/chatbox/room.html
<!-- chat/templates/chat/room.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>Chat Room</title>
</head>
<body>
    <h1>Welcome {{ user.user_name }}</h1><br>
    <div id="chatroom">
        <p id="online_users">
            <ul id="online">

            </ul>
            <!--{% if user_list%}
                {% for user in user_list %}
                    {{ user }} is online. <br>
                {% endfor %}
            {% endif %}-->
        </p>
    </div>
    <div style="width:80%; max-width:1000px; height:400px; max-height:400px; overflow:auto">
        <ul id="chat-log" style="list-style-type:none; width:inherit; padding:0px; margin:0px">
            
        </ul>
    </div>
    <input id="chat-message-input" type="text" size="100"/><br/>
    <input id="chat-message-submit" type="button" value="Send"/>
</body>
<script>
    var roomName = {{ room_name_json }};
    var current_user = {{ user_ob }};

    var chatSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chatbox/' + roomName + '/'
        );
    
    /*var onlineSocket = new WebSocket(
        'ws://' + window.location.host +
        '/ws/chatbox/' + roomName + '/'
        );*/
    
    chatSocket.onopen = function(e) {
        document.querySelector('#online_users').innerHTML += ('online...<br>');
        chatSocket.send(JSON.stringify({
            'user': current_user,
            'message': None,
        }));

        var init = JSON.parse(e.data);
        var connected_user = init['online'];
        document.querySelector('#online').innerHTML = '';
        for (users in connected_user) {
            document.querySelector('#online').innerHTML += ('<li style="color:green" id="' + connected_user[users] + '">' + connected_user[users] + ' is online....' + '</li>');
        }
    };

    chatSocket.onmessage = function(e) {
        var data = JSON.parse(e.data);
        var online = data['online'];
        document.querySelector('#online').innerHTML = '';
        for (users in online) {
            document.querySelector('#online').innerHTML += ('<li style="color:green" id="' + online[users] +'">' + online[users] + ' is online.' + '</li>');
        }

        if (data['message']) {
            var message = data['message'];
            var sender = data['user'];
            if (sender == current_user) {
                document.querySelector('#chat-log').innerHTML += ('<li style="color:red; text-align:right">' + sender + ':' + message + '</li>');
            }
            else {
                document.querySelector('#chat-log').innerHTML += ('<li style="color:blue; text-align:left">' + sender + ':' + message + '</li>');
            }
        }
        
    };

    chatSocket.onclose = function(e) {
        console.log('bye.....');
        console.error('Chat socket closed unexpectedly');
    };

    document.querySelector('#chat-message-input').focus();
    document.querySelector('#chat-message-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#chat-message-submit').click();
        }
    };

    document.querySelector('#chat-message-submit').onclick = function(e) {
        var messageInputDom = document.querySelector('#chat-message-input');
        var message = messageInputDom.value;
        chatSocket.send(JSON.stringify({
            'message': message,
            'user': current_user
        }));

        messageInputDom.value = '';
    };

/*    onlineSocket.onopen = function(event) {
        document.querySelector('#online_users').innerHTML += ('online...\n');
        
        onlineSocket.send(JSON.stringify({
            'online_user': current_user
        }));
    };

    onlineSocket.onmessage  = function(event) {
        var users = JSON.parse(event.data);
        document.querySelector('#online_users').innerHTML += ('online....\n');

        if (users['connected']) {
            var online = users['connected'];
            for (user in online) {
                document.querySelector('#online').innerHTML += ('<li style="color:green" id="' + user +'">' + user + ' is online.' + '</li>');
            }
        }
    };

    onlineSocket.onclose = function(event) {
        document.queryselector('#'+ current_user).innerHTML = (current_user + ' is offline.' );
        document.queryselector('#'+ current_user).style = ('color:black');
        console.message('User went offline');
    };*/

</script>
</html>